---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - secrets.k8s.bendronen.com
  resources:
  - secretsummaries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.k8s.bendronen.com
  resources:
  - secretsummaries/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.k8s.bendronen.com
  resources:
  - secretsummaries/status
  verbs:
  - get
  - patch
  - update
