# permissions for end users to edit secretsummaries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-secret-summary
    app.kubernetes.io/managed-by: kustomize
  name: secretsummary-editor-role
rules:
- apiGroups:
  - secrets.k8s.bendronen.com
  resources:
  - secretsummaries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.k8s.bendronen.com
  resources:
  - secretsummaries/status
  verbs:
  - get
