apiVersion: secrets.k8s.bendronen.com/v1alpha1
kind: SecretSummary
metadata:
  labels:
    app.kubernetes.io/name: kube-secret-summary
    app.kubernetes.io/managed-by: kustomize
  name: secretsummary-sample
spec:
  # TODO(user): Add fields here
